### ISSUE TITLE
LOCATION MANAGER ERROR

### ISSUE THREAD

**Issue by enijar** [bradoyler/point2place#1]
I installed `corelocationcli` via `brew` with the command in the README:

```
brew cask install corelocationcli
```

When running the command in the README:

```
CoreLocationCLI -format "%longitude,%latitude"
```

I get the following error:

LOCATION MANAGER ERROR: The operation couldn’t be completed. (kCLErrorDomain error 0.)

**Comment by bradoyler** [comment]
that repo is @ https://github.com/fulldecent/corelocationcli
